# config/packages/monolog.yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/error.log"
            level: error
            channels: ["!event", "!doctrine", "!console"]
        infrastructure:
            type: stream
            path: "%kernel.logs_dir%/infrastructure.log"
            level: debug
            channels: ["event", "doctrine", "console"]
