---
stages:
  - validation
  - docker
  - acceptance

# Speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vendor

test:
  stage: validation
  image: composer:2.1
  before_script:
    # Install all project dependencies
    - composer install
  script:
    - echo "Checking code standars and running Tests"
    - make cs
    - make test

## Uncomment the following sections to enable docker, image building and
## acceptance

# build:
#   stage: build
#   image: # Add an image to build your service
#   artifacts:
#     paths:
#       - bin/
#   script:
#     - echo do something to build the binary or whatever

# build_image:
#   stage: docker
#   image: docker:latest
#   variables:
#     DOCKER_DRIVER: overlay2
#     DOCKER_TLS_CERTDIR: ""
#     DOCKER_HOST: tcp://docker:2375/
#   services:
#     - docker:dind
#   script:
#     - echo As a helper here you have a sample of how to build and push a \
#     docker image to the provided gitlab registry.
#     - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
#     - docker build . -t ${CI_REGISTRY_IMAGE}:latest
#     - docker push ${CI_REGISTRY_IMAGE}:latest

## Uncomment the acceptance step and do not remove or edit, this step is
## required for us to accept your submission!

# acceptance:
#   image: cabify/challenge:latest
#   stage: acceptance
#   only:
#     - master
#   dependencies: []
#   services:
#     - name: ${CI_REGISTRY_IMAGE}:latest
#       alias: pooling
#   script:
#     - /harness --address http://pooling:9091 acceptance
