status:
    path: /status
    methods: GET
    controller: Gonsandia\CarPoolingChallenge\Infrastructure\UI\Web\CheckServiceStatusController::index

cars:
    path: /cars
    methods: PUT
    controller: Gonsandia\CarPoolingChallenge\Infrastructure\UI\Web\LoadAvailableCarsController::index

dropoff:
    path: /dropoff
    methods: POST
    controller: Gonsandia\CarPoolingChallenge\Infrastructure\UI\Web\DropOffController::index


locate:
    path: /locate
    methods: POST
    controller: Gonsandia\CarPoolingChallenge\Infrastructure\UI\Web\LocateCarController::index

journey:
    path: /journey
    methods: POST
    controller: Gonsandia\CarPoolingChallenge\Infrastructure\UI\Web\PerformJourneyController::index
